name: Release Template

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  release_template:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      iam_role_to_assume: ${{ secrets.ROLE_ARN }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure AWS Credentials
        if: ${{ env.iam_role_to_assume != '' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.iam_role_to_assume }}
          aws-region: us-east-1
      - name: Build and Publish
        run: |-
          cd server/scripts
          bash push-to-ecr.sh
      - name: Copy Deployment Templates to S3
        env:
          S3_BUCKET: ${{ secrets.ASSET_BUCKET }}
          S3_PREFIX: swift-chat/latest/
        run: aws s3 sync server/template/ s3://$S3_BUCKET/$S3_PREFIX --acl public-read
